class PlatformException(Exception): ...

class CredentialsNotSatisfiedException(PlatformException): ...

class CredentialsNotSetException(PlatformException): ...

class CaptchaFailedToSolveException(PlatformException): ...

class LoginFailedException(PlatformException): ...

class GameNotFoundException(PlatformException): ...

class NoPermissionException(PlatformException): ...

class UnauthorizedAccessException(PlatformException): ...